version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pizza-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizzaonline-db
    ports:
      - "5432:5432"
    volumes:
      - pizza_data:/var/lib/postgresql/data

volumes:
  pizza_data:
